import random
def xingar():
    xingamentos = ["Tua Mãe é tão feia que quando seu pai acordou da bebedeira ele achou que tava no inferno",
                   "Tua Mãe é tão gorda que usam o umbigo dela pra lavar roupa",
                   "Tua Mãe é tão gorda que quando transo com ela, dou duas cambalhotas e ainda estou em cima dela",
                   "Tua Mãe é tão gorda que ela ficou entalada num buraco negro",
                   "Tua Mãe é tão burra que ela demora 2 minutos para assistir ao Se Vira Nos 30",
                   "Tua Mãe é tão gorda que quando ela saiu na rua com uma capa de chuva amarela, todos acharam que o Sol havia caído",
                   "Tua Mãe é tão idiota que tropeçou no fio de um telefone celular",
                   "Tua Mãe é tão gorda que para dar um abraço de ano novo nela, tem que começar em junho",
                   "Aparentemente, todo mundo que discutiu com você já fez sexo com a sua mãe",
                   " Quando você nasceu, sua mãe achou que você era um enorme pedaço de bosta",
                   " Tua Mãe é a resposta mais usada para qualquer pergunta ofensiva que você faça. Por exemplo: “Em buraco de cobra, tatu caminha dentro?” Ao que seu oponente responde: “TUA MÃE!",
                   " Tua Mãe é, na verdade, o Teu Pai com uma peruca",
                   " Tua Mãe é tão cabeçuda que quando vai amarrar os sapatos ela da cambalhota",
                   " Tua Mãe é tão feia que quando ela deita na areia da praia, os gatos tentam enterrá-la",
                   " Tua Mãe é tão suja que ela toma banho com vaporet",
                   " Tua Mãe é tão gorda que quando ela vestiu uma camiseta com um grande H, um helicóptero veio e pousou nela",
                   " Tua Mãe é tão gorda que quando ela caiu no Grand Canyon ela encalhou",
                   " Tua Mãe é tão velha que se eu chupar o peito dela, vai sair leite em pó",
                   " Tua Mãe é tão gorda que ela rolou em cima de quatro moedas de 25 centavos e fez um real",
                   " Tua Mãe é tão gorda que ela teve que ir ao SeaWorld para ser batizada",
                   " Tua Mãe é tão gorda que que quando vai ao cinema senta perto de todo mundo",
                   " Tua Mãe tem uma bunda tão grande que precisa cagar no tanque",
                   " Tua Mãe tem tanto bigode que a gente não sabe se ela tá de frente ou tá de costas",
                   " Tua Mãe é tão gorda, que tira foto 3×4 via satélite",
                   " Tua Mãe é tão gorda que ela usa bumerangue pra colocar o cinto",
                   " Tua Mãe é tão gorda que pra faze sexo anal nela você precisa de habilitação especial para rally",
                   " Tua Mãe é tão gorda que o cinto dela é a via láctea",
                   " Tua Mãe é tão gorda que tem um CEP só pra ela",
                   " Tua Mãe pilota caminhão sem camisa e masca Durepox ao mesmo tempo",
                   " Tua Mãe quando tira o sutiã diz: Como o piso tá gelado",
                   " Tua Mãe é tão gorda que foi declarada um planeta",
                   " Tua Mãe tem o bafo tão fedido que seus dentes se abaixam quando ela fala",
                   " Tua Mãe é tão gorda que ela tem que passar as roupas em cima de uma rodovia",
                   " Tua Mãe é tão gorda que ela usa um colchão como absorvente",
                   " Tua Mãe é tão gorda que ela pula amarelinha assim: são paulo, tocantins, bahia, amapá",
                   " Tua Mãe é tão gorda que vulcanologistas estudam as espinhas dela",
                   " Tua Mãe é tão gorda que quando ela usa salto fino, ela acha petróleo",
                   " Tua Mãe é tão gorda que quando ela sobe na balança aparece “Um por vez, por favor”",
                   " Tua Mãe é tão velha que o numero do INSS dela é 1",
                   " Tua Mãe é tão velha que ela deve 1 real pra Jesus",
                   " Tua Mãe é tão velha que quando Deus disse “E que se faça a luz” ela apertou o interruptor",
                   " Tua Mãe é tão feia que quando ela joga bumerangue ele não volta",
                   " Tua Mãe é tão feia que tua avo teve que alimentá-la do outro lado do quarto com um estilingue",
                   " Tua Mãe é tão magra que ela tem que correr embaixo do chuveiro pra se molhar",
                   " Tua Mãe tem óculos tão grossos que quando ela olha num mapa ela vê pessoas acenando",
                   " Tua Mãe tem peitos tão grandes que quando ela corre ela fica com os olhos roxos",
                   " Tua Mãe tem tantas cáries que parece que ela tem dados na boca",
                   " Tua Mãe é tão feia que tem filhos de 3 e 9 anos e todos pensam que são gêmeos pois não acreditam que comeram ela 2 vezes",
                   " Tua Mãe é tão biscate que ela se maturba com britadeira de asfalto",
                   " A sua mãe é tão gorda que as pessoas fazem cooper em volta dela, para fazer exercícios!",
                   "A sua mãe é tão gorda que quando ela foi ao cinema, sentou perto de todo mundo!",
                   "A sua mãe é tão gorda que quando ela estava flutuando pelo oceano, alguns portugueses gritaram: “TERRA À VISTAAAAAAAA”",
                   "A sua mãe é tão gorda que quando ela deitou na praia, as pessoas correram pra volta dela gritando: “FREEEE WILLYYYYYYYY”",
                   "A sua mãe é tão gorda que quando ela vai em um restaurante, olha para o menu e diz: “Isso aqui de entrada está bom”",
                   'A sua mãe é tão gorda que quando ela veste uma capa amarela, as pessoas gritam: “TÁXIIIIIIIIIIIIIIII”',
                   ' A sua mãe é tão gorda que ela teve que ir ao Sea World para ser batizada!',
                   ' A sua mãe é tão gorda que ela tem que usar uma rolo de pintura como baton!',
                   ' A sua mãe é tão gorda que ela tem que tirar as calças para alcançar os bolsos!',
                   ' A sua mãe é tão gorda que quando ela pula no Bungee Jump, ela traz a ponte junto!',
                   ' A sua mãe é tão gorda que quando ela senta em volta da casa, ela SENTA MESMO EM VOLTA DA CASA!!',
                   ' A sua mãe é tão gorda que quando ela sobe numa balança, o mostrador diz “Um por vez, por favor”',
                   ' A sua mãe é tão gorda que quando ela sobe numa balança, o mostrador diz “To be continued”',
                   ' A sua mãe é tão gorda que o pescoço dela parece dois cachorros-quente!',
                   ' A sua mãe é tão gorda que ela tem o seu próprio código de área!',
                   ' A sua mãe é tão gorda que Deus não pôde colocar luz na Terra até ela se mexer!',
                   ' A sua mãe é tão gorda que a NASA teve que lançar um satélite em volta dela!',
                   ' A sua mãe é tão gorda que nem o Bill Gates pode pagar a ela uma lipoaspiração!',
                   ' A sua mãe é tão gorda que eu tive que pegar um trem e dois ônibus só para chegar no lado bom dela!',
                   ' A sua mãe é tão gorda que quando ela vai num parque de diversões, as pessoas tentam andar nela!',
                   ' A sua mãe é tão gorda que ela foi confundida com a bola de boliche de Deus!',
                   ' A sua mãe é tão gorda que ela rolou por quatro moedas de 25 centavos e fez um real!',
                   ' A sua mãe é tão gorda que quando ela deita na praia, ninguém mais pega sol!',
                   ' A sua mãe é tão gorda que quando ela pula no Bungee Jump, vai direto para o inferno!',
                   ' A sua mãe é tão gorda que quando ela pula no ar, ela fica entalada!',
                   ' A sua mãe é tão gorda que as fotos de formatura dela teve que ser panorâmica!',
                   ' A sua mãe é tão gorda que está nos dois lados da família!',
                   ' A sua mãe é tão gorda que quando ela caiu fez o Grand Canyon!',
                   ' A sua mãe é tão gorda que ela tem que usar um video-cassette como pager!',
                   ' A sua mãe é tão gorda que ela tem que comprar duas passagens aéreas!',
                   ' A sua mãe é tão gorda que quando ela caiu, se cansou e caiu no sono tentando se levantar de novo!',
                   ' A sua mãe é tão gorda que quando eu tentei dar a volta nela, acabou a gasolina!',
                   ' A sua mãe é tão gorda que os animais no Zôo alimentam ela!',
                   ' A sua mãe é tão gorda que ela foi batizada numa marina!',
                   ' A sua mãe é tão gorda que ela fica em dois fusos horários!',
                   ' A sua mãe é tão gorda que não consegue amarrar seus próprios sapatos!',
                   ' A sua mãe é tão gorda que quando ela deitou na praia, os carinhas do green peace tentaram empurrar ela de volta pro mar!',
                   ' A sua mãe é tão gorda que as únicas fotos que você tem dela foram tiradas por um satélite!',
                   ' A sua mãe é tão gorda que ela sentou num dollar e tirou uma meleca do nariz do George Washington!',
                   ' A sua mãe é tão gorda que ela poderia ter aparecido no E.T., mas quando ela cruzou a lua numa bicicleta, aquela bruxa causou um eclipse!',
                   ' A sua mãe é tão gorda que ela foi batizada num oceano!',
                   ' A sua mãe é tão gorda que ela tem que passar as suas roupas numa auto-estrada!',
                   ' A sua mãe é tão gorda que eles amarraram uma corda nos ombros dela e a arrastaram num túnel, para limpá-lo!',
                   ' A sua mãe é tão gorda que quando ela foi atropelada por um ônibus, ela falou: “Quem atirou essa pedra?”',
                   ' A sua mãe é tão gorda que o departamento de meteorologia teve que nomear os seus peidos!',
                   ' A sua mãe é tão burra que quando viu a placa NC-17 (não permitido abaixo de 17), ela foi em casa e arrumou 16 amigos!',
                   ' A sua mãe é tão burra que quando ela ficou trancada numa quitanda, ela morreu de fome!',
                   ' A sua mãe é tão burra que ela tentou colocar os M&M’s em ordem alfabética!',
                   ' A sua mãe é tão burra que ela foi atropelada por um carro estacionado!',
                   ' A sua mãe é tão burra que ela pode se enroscar em um telefone sem fio!',
                   'A sua mãe é tão burra que ela vendeu o carro para conseguir dinheiro pra gasolina!',
                   ' A sua mãe é tão burra que ela comprou uma lanterna � energia solar!',
                   ' A sua mãe é tão burra que ela perguntou: “Qual é o número do 911?”',
                   ' A sua mãe é tão burra que ela levou uma régua para a cama para medir o quanto ela dormiu!',
                   ' A sua mãe é tão burra que quando ela leu uma nota no seu trabalho, dizendo para não escrever abaixo da linha pontilhada, ela escreveu ” O.K.”',
                   ' A sua mãe é tão burra que ela roubou uma amostra grátis!',
                   ' A sua mãe é tão burra que ela faz parecer Beavis e Butt-Head ganhadores de prêmios Nobel!',
                   ' A sua mãe é tão burra que quando perguntaram “sexo?” numa ficha, ela marcou “H, e talvez amanhã também”',
                   ' A sua mãe é tão burra que quando você fica perto dela, você escuta o som do oceano!',
                   ' A sua mãe é tão burra que ela pensa que Fleetwood Mac é um novo hamburguer no McDonald’s!',
                   ' A sua mãe é tão burra que ela comprou uma câmera de vídeo para gravar os programas da tv a cabo, em casa!',
                   ' A sua mãe é tão burra que quando ela pulou a janela, subiu!',
                   ' A sua mãe é tão burra que quando ela assiste os 3 Patetas, ela toma notas!',
                   ' A sua mãe é tão feia que quando ela entrou no concurso de feiúra, eles disseram “Desculpe, não aceitamos profissionais”',
                   ' A sua mãe é tão feia que quando ela olhou pela janela foi presa por molestar a paz pública!',
                   ' A sua mãe é tão feia que quando ela nasceu, a mãe dela falou “Que tesouro!” e o pai dela disse “É, vamos enterrá-lo.”',
                   ' A sua mãe é tão feia que eles pressionaram a cara dela contra massa de biscoito para fazer GORILLA BISCUITS!',
                   ' A sua mãe é tão feia que eles não deram a ela uma fantasia quando foi fazer o teste do Star Wars!',
                   ' A sua mãe é tão feia que ao invés de colocar a corda do Bungee Jump nos seus tornozelos, eles colocam no seu pescoço!',
                   ' A sua mãe é tão feia que tem 364 dias extras para se vestir pro Dia das Bruxas!',
                   ' A sua mãe é tão feia que quando ela entra em um banco, eles desligam as câmeras de vigilância!',
                   ' A sua mãe é tão feia que a sua avó devia estar bêbada para dar de mamar a ela!',
                   ' A sua mãe é tão feia que a mãe dela tinha que amarrar um bife em volta do seu pescoço para conseguir que os cães brincassem com ela!',
                   ' A sua mãe é tão feia que quando ela caminha na rua, as pessoas dizem: “Droga, já é o Dia das Bruxas?”',
                   ' A sua mãe é tão feia que o governo mudou a data do Dia das Bruxas para a data de aniversário dela!',
                   ' A sua mãe é tão feia que faz uma cebola chorar!',
                   ' A sua mãe é tão feia que filmaram o “Gorillas in the Mist” enquanto ela tava no banho!',
                   ' A sua mãe é tão feia que eles pressionaram a cara dela contra massa de biscoito para fazer MONSTER BISCUITS!',
                   ' A sua mãe é tão feia que quando ela tentou tomar um banho, a água pulou fora!',
                   ' A sua mãe é tão feia que no Dia das Bruxas ela tem que dizer “Travessuras ou Gostosuras” pelo telefone!',
                   ' A sua mãe é tão feia que ela tem que embebedar o seu bebê para dar de mamar a ele!',
                   ' A sua mãe é tão feia que ela transformou a Medusa em pedra!',
                   ' A sua mãe é tão feia que as pessoas se fantasiam dela no Dia das Bruxas!',
                   ' A sua mãe é tão feia que quando ela deita na areia da praia, os gatos tentam enterrá-la!',
                   ' A sua mãe é tão feia que assusta até as baratas!',
                   ' A sua mãe é tão feia que o seu pai leva ela junto pro trabalho para não ter que dar um beijo de despedida!',
                   ' A sua mãe é tão velha que eu falei pra ela agir como uma pessoa da sua idade, e a desgraçada morreu!',
                   ' A sua mãe é tão velha que ela tem o número do pager de Jesus!',
                   ' A sua mãe é tão velha que o número de segurança social dela é 1!',
                   ' A sua mãe é tão velha que quando ela estava na escola não existia aulas de história!',
                   ' A sua mãe é tão velha que ela deve a Jesus 3 pratas!',
                   ' A sua mãe é tão velha que no certificado de nascimento dela diz: “Expirado”',
                   ' A sua mãe é tão velha que ela fugia dos dinossauros!',
                   ' A sua mãe é tão velha que o certificado de nascimento dela é em números romanos!',
                   ' A sua mãe é tão velha que ela sentava atrás de Jesus na terceira série!',
                   ' A sua mãe é tão pobre que quando eu vi ela chutando uma lata no meio da rua, eu perguntei o que ela estava fazendo, e ela disse: “Me mudando.”',
                   ' A sua mãe é tão pobre que quando eu toco a campainha eu escuto o barulho da descarga!',
                   ' A sua mãe é tão pobre que quando eu toco a compainha, ela diz: “DING DONG”',
                   ' A sua mãe é tão pobre que a sua família come cereal com garfos para economizar leite!',
                   ' A sua mãe é tão negra que quando ela foi a aula de noite não ganhou presença!',
                   ' A sua mãe é tão negra que ela cospe leite achocolatado!',
                   ' A sua mãe é tão negra que ela consegue deixar impressões digitais em pedaço de carvão!',
                   ' A sua mãe é tão negra que ela tem que usar luvas brancas para comer chocolate para não morder os dedos!',
                   ' A sua mãe é tão baixa que ela teve que usar uma escada para pegar uma moeda no chão!',
                   ' A sua mãe é tão baixa que ela consegue dar saltos mortais debaixo da cama!',
                   ' A sua mãe é tão piranha que quando ela vai ao cabeleleiro, ela fala ao estilista para cortar o seu cabelo e levanta a sua saia!',
                   ' A sua mãe é tão nojenta que ela fez o Speed Stick parar!',
                   ' A sua mãe é tão nojenta que ela atrai caranguejos para a praia!',
                   ' A sua mãe é tão nojenta que o dono da peixaria paga para ela ir embora!',
                   ' A sua mãe é tão nojenta que a merda dela fica feliz em escapar!',
                   ' A sua mãe é tão nojenta até o Ozzy Osbourne se recusou a morder a cabeça dela fora!',
                   ' A sua mãe é tão nojenta que telefonei pra ela para sex phone e ela me passou uma infecção no ouvido!',
                   ' A sua mãe é como uma dobradiça de uma porta – Todo mundo dá uma viradinha!',
                   ' A sua mãe é como um aparelho de T.V. – até um garotinho de 3 anos pode ligá-la!',
                   ' A sua mãe é como um ônibus – 50 centavos e você sobe nela!',
                   ' A sua mãe é como uma geladeira – todo mundo coloca a carne nela!',
                   ' A sua mãe é como um ônibus – os caras sobem e descem nela o dia todo!',
                   ' A sua mãe é como um aspirador – uma boa sugada!',
                   ' A sua mãe é tão cabeluda que ela chega a ter dreadlocks no suvaco!',
                   ' A sua mãe é tão cabeluda que o Pé Grande está tirando a foto dela!',
                   ' A sua mãe é tão vadia que eu poderia ter sido o seu pai, mas o cara que estava atrás de mim na fila tinha o troco correto!',
                   ' A sua mãe tem o nariz tão grande que você pode ir jogar boliche com as suas melecas!',
                   ' A sua mãe tem o nariz tão grande que ela faz o Pinóquio parecer um gatinho!',
                   ' A sua mãe é tão grudenta que ela usa bacon como band-aid!',
                   ' A sua mãe é tão grudenta que a Texaco compra óleo dela!',
                   ' A sua mãe tem os dentes tão amarelos que o tráfego pára quando ela sorri!',
                   ' A sua mãe tem os dentes tão amarelos que ela cospe manteiga!',
                   ' A sua mãe é tão preguiçosa que ela pensa que uma família com duas fontes de renda é onde o pai tem dois empregos!',
                   ' A sua mãe é tão magra que quando ela virou de lado, desapareceu!',
                   ' A sua mãe é tão careca que dá para ver o que tem na sua mente!',
                   ' A sua mãe é tão careca que quando ela tomou banhou, fez uma lavagem cerebral!',
                   ' A sua mãe é tão reta que ela chega a ter ciúmes de um muro!',
                   ' A sua mãe tem uns óculos tão grossos que quando ela olha num mapa, ela consegue ver as pessoas acenando!',
                   ' A sua mãe tem uns óculos tão grossos que ela consegue olhar o futuro!',
                   ' A sua mãe tem cabelos verdes e pensa que é uma árvore!',
                   ' A sua mãe tem 10 dedos – todos na mesma mão!',
                   ' A sua mãe tem uma perna curta e caminha em círculos!',
                   ' A sua mãe tem os braços tão curtos que ela não consegue aplaudir!',
                   ' A sua mãe tem tantos dentes faltando que parece que a língua dela está na cadeia!',
                   ' A casa da sua mãe é tão pequena que quando ela encomenda uma pizza grande tem que ir comê-la na rua!',
                   ' A casa da sua mãe é tão suja que ela tem que limpar os pés antes de pisar na rua!',
                   ' A sua mãe tem uma cabeça tão grande que chega a aparecer em um radar!',
                   ' A sua mãe tem uma cabeça tão pequena que ela teve uma orelha cortada fora e morreu!',
                   ' A sua mãe tem uma cabeça tão pequena que ela usa saquinhos de chá como travesseiro!',
                   ' A sua mãe é duas vezes o homem que você é!',
                   ' A sua mãe não tem um dedo e só consegue contar até 9!',
                   ' A sua mãe é tão burra que ela nasceu no dia da Independência e não consegue se lembrar do seu aniversário!',
                   ' Se meu cachorro fosse tão feio quanto sua mãe, eu depilaria a sua bunda e o faria caminhar de costas!',
                   ' A sua mãe tem uma boca tão grande que ela fala num som Dolby Sorround!',
                   ' O bafo da sua mãe fede tanto que quando ela grita os dentes dela se abaixam!',
                   ' A sua mãe é tão gorda que quando ela vestiu uma camiseta com um grande X, um helicóptero veio e pousou nela!',
                   ' A sua mãe é tão burra que ela acha que menoPAUSA é um botão!',
                   ' A sua mãe é tão burra que ela acha que socialismo é fazer festas!',
                   ' A sua mãe é tão burra que ela foi despedida da fábrica do M&M’s por jogar fora os W’s!',
                   ' A sua mãe é como uma árvore de natal: todo mundo pendura bolas nela!',                   
                   ' A sua mãe é como o McDonald’s: Bilhões e bilhões de pessoas servidas!',                   
                   ' A sua mãe é como sorvete: todo mundo dá uma lambidinha!',                   
                   ' A sua mãe é como um bolo de aniversário: todo mundo tira um pedaço!',                   
                   ' A sua mãe é como mostarda: se esparrama fácil!',
    ]
    return random.choice(xingamentos)
